apiVersion: backstage.io/v1alpha1
kind: ${{ values.entityKind }}
metadata:
  name: ${{ values.repoName }}
  annotations:
    github.com/project-slug: ${{ values.orgName }}/${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.projectName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-label-selector: 'app=${{ values.projectName }}'
    argocd/app-name: ${{ values.repoName }}-tekton-ci
    argocd/instance-name: default
    argocd/namespace: ${{ values.namespace }}
  tags:
    - springboot
    - api
    - microservice
spec:
  type: ${{ values.applicationType }}
  lifecycle: ${{ values.lifecycle }}
  owner: ${{ values.owner }}
  providesApis:
    - ${{ values.repoName }}-api
